### ISSUE TITLE
"yarn dev" does not start app

### ISSUE THREAD

**Issue by OskarZyg** [Exeteres/electron-nuxt-ts#22]
This is either an issue with the project itself or the lack of documentation:
After cloning the repository:
```bash
oskar@oskarspc:~/Documents/GitHub/electron-nuxt-ts$ yarn install
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "nuxt-class-component > vue-class-component@7.2.3" has unmet peer dependency "vue@^2.0.0".
warning "nuxt-class-component > vuex-class@0.3.2" has unmet peer dependency "vue@^2.5.0".
warning "nuxt-class-component > vuex-class@0.3.2" has unmet peer dependency "vuex@^3.0.0".
[4/4] Building fresh packages...
Done in 9.01s.
oskar@oskarspc:~/Documents/GitHub/electron-nuxt-ts$ yarn dev
yarn run v1.22.11
$ yarn build:main && concurrently -k -n main,renderer -c blue,green "cross-env NODE_ENV=development electron ." "nuxt-ts dev"
$ tsc -p tsconfig.main.json
[renderer] ℹ Listening on: http://localhost:3000/
[main] (node:46560) UnhandledPromiseRejectionWarning: Error: Invalid header: Does not start with Cr24
[main]     at crxToZip (/home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/unzip-crx/dist/index.js:32:15)
[main]     at /home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/unzip-crx/dist/index.js:57:32
[main]     at callHanler (/home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/yaku/lib/yaku.js:719:16)
[main]     at tryCatcher (/home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/yaku/lib/yaku.js:436:32)
[main]     at /home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/yaku/lib/yaku.js:575:38
[main]     at flush (/home/oskar/Documents/GitHub/electron-nuxt-ts/node_modules/yaku/lib/yaku.js:478:17)
[main]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[main] (node:46560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[main] (node:46560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[renderer] ℹ Preparing project for development
[renderer] ℹ Initial build may take a while
[renderer] ✔ Builder initialized
[renderer] ✔ Nuxt files generated
[renderer] 
[renderer]  WARN  Browserslist: caniuse-lite is outdated. Please run:
[renderer] npx browserslist@latest --update-db
[renderer] 
[renderer] ℹ Compiling Client
[renderer] ℹ Starting type checking service...

[renderer] ✔ Client: Compiled successfully in 2.86s
[renderer] ℹ Type checking in progress...
[renderer] ℹ Waiting for file changes
[renderer] ℹ Memory usage: 132 MB (RSS: 245 MB)
[renderer] ℹ Listening on: http://localhost:3000/
[renderer] ℹ No type errors found
[renderer] ℹ Version: typescript 3.8.3
[renderer] ℹ Time: 4644 ms
```

No Window is created.

Building the app, however, does create a window.

OS: Pop!_OS 20.04 (Ubuntu 20.04 fork)

**Comment by Exeteres** [comment]
Hello and sorry for the delayed reply.

Unfortunately, this project is out of date. I tried to quickly update some dependencies, but it turned out to be not that easy. 
In any case, if the project cannot remain fully up-to-date, it is dangerous to use it.
I will have to temporarily declare it unsupported.

Lately, a lot of new things have happened, in the both electron and vue worlds. 
It is possible that in the future I will have a little time to revive this project using new technologies. 
If someone needs it, of course.
